---
title: 'Case Study 01: Comparison of the average BMI of PPGEE-UFMG students over two
  semesters'
author: "Hernane Braga, Lucas Carneiro and Vinicius Ferreira"
date: "January 23, 2021"
output:
  html_document:
    df_print: paged
  pdf_document:
    fig_caption: yes
---

## Summary
```{r, child=c('blocks/summary.Rmd')}

```

## Experimental design

### First Experiment
```{r, child=c('blocks/experiment1.Rmd')}

```

### Second Experiment
```{r, child=c('blocks/experiment2.Rmd')}

```

### Third Experiment
```{r, child=c('blocks/experiment3.Rmd')}

```

### Experiment Details
```{r, child=c('blocks/experiment_conclusion.Rmd')}

```

## Description of the data collection
```{r, child=c('blocks/data_treatment.Rmd')}

```

## Exploratory Data Analysis
```{r, child=c('blocks/exploratory_analysis.Rmd')}

```

## Statistical Analysis

### First Test
```{r, child=c('blocks/test1.Rmd')}

```

### Second Test
```{r, child=c('blocks/test2.Rmd')}

```

### Third Test
```{r, child=c('blocks/test3.Rmd')}

```

## Checking Model Assumptions
```{r, child=c('blocks/model_check.Rmd')}

```

## Conclusions and Recommendations
```{r, child=c('blocks/conclusion.Rmd')}

```