---
output:
  pdf_document: default
  html_document: default
---

<!-- 1. Formulação das hipóteses de teste; -->
<!-- 2. Cálculo dos tamanhos amostrais (quantas instâncias testar? Quantas repetições de cada algoritmo por -->
<!-- instância?); -->
<!-- 3. Coleta e tabulação dos dados; -->
<!-- 4. Teste das hipóteses; -->
<!-- 5. Estimação da magnitude da diferença entre os métodos (incluindo intervalo de confiança); -->
<!-- 6. Verificação das premissas dos testes; -->
<!-- 7. Derivação de conclusões; -->
<!-- 8. Discussão sobre possíveis limitações do estudo e sugestões de melhoria. -->

A fim de solucionar problemas de otimização, heurísticas são utilizadas a fim de encontrar uma solução viável em tempo hábil, dado que algoritmos para encontrar a solução ótima exata levariam anos para obter sucesso. Uma dessas heurísticas são algoritmos baseados em população, que utilizam um conjunto de soluções-candidatas e, com uma série de operações de variação e seleção nelas, exploram o espaço amostral do problema em busca do ótimo. Neste ensaio, utiliza-se o método de evolução diferencial.

Este trabalho explora como duas diferentes configurações ([Tabela 1](#tabela1)) do método citado impactam no resultado, observando qual destas obtém melhor desempenho. Para testar as configurações, utiliza-se uma função de Rosenbrock, com o intervalo de dimensões de interesse de $[2,150]$.

<a id="tabela1"></a>

| Configuração | Mutação           | Recombinação       |
|--------------|-------------------|--------------------|
| 1            | Aleatória (f = 4) | Aritmética         |
| 2            | Melhores (f = 3)  | Binária (cr = 0.7) |


As próximas etapas deste estudo de caso é apresentado a seguir:

1. Formulação das hipóteses de teste;
2. Cálculo dos tamanhos amostrais;
3. Coleta e tabulação dos dados;
4. Teste das hipóteses;
5. Estimação da magnitude da diferença entre os métodos;
6. Verificação das premissas dos testes;
7. Conclusões
8. Discussão sobre os processos do estudo

