---
output:
  pdf_document: default
  html_document: default
---

Coleta e tratamento.

Os dados que possuiam valores faltantes foram retirados do base, resultando em um novo total de 56420 dados. Após isso, a variável data foi transformada em três novas: Dia, Mês e Ano. Estas variáveis não serão utilizadas pelos modelos, mas permitem uma melhor organização da base de dados.

blablabla

A correlação entre as variáveis de interesse foram calculadas, este processo permite verificar se existem variáveis que podem ser consideradas redundantes e, portanto, eliminadas do treinamento dos modelos.

```{r correlation_calc, message=FALSE}

library(corrplot)
corrplot(cor(DADOS), method="number",type = "upper")

```

As correlações indicam que... blablabla

Antes de realizar o treinamento dos modelos, aplicou-se uma normalização mínimo-máximo nas variáveis independentes (variáveis de entrada) para que a magnitude dos seus valores não impactem negativamente na convergência dos algoritmos e para que as variáveis tenham igual influência no treinamento.

