---
output:
  pdf_document: default
  html_document: default
---
The original data contained two datasets: the first had Electrical Engineering graduate and postgraduate students from the 2016/2 semester. The last described only postgraduate students on the 2017/2 semester.

Since the target variable is the BMI population, the following steps are applied for data cleaning: 

2016 Dataset:

- Calculate BMI for all samples
- Selecting only postgraduate students

2017 Dataset:

- Rename columns following 2016 standard
- Calculate BMI for all samples

After data transformations, the analysis datasets were created:

- **male_students**: male students from the 2016/2 and 2017/2 semester
- **female_students**: female students from the 2016/2 and 2017/2 semester
- **male_students2016**, female_students2016: male and female students from the 2016/2 semester
- **male_students2017**, female_students2017: male and female students from the 2017/2 semester


```{r loaddata}
library(car)

# Loading dataset
datapath <- '../data/'

dataset_2016 <- read.csv(paste(datapath,'imc_20162.csv',sep = "/"), sep=',')
dataset_2017 <- read.csv(paste(datapath,'CS01_20172.csv',sep = "/"), sep=';')


# Renaming columns
names(dataset_2017)[names(dataset_2017) == "Sex"] <- "Gender"
names(dataset_2017)[names(dataset_2017) == "height.m"] <- "Height.m"


# Selecting variables
model_var <- c("Height.m", "Weight.kg", "IMC")


# Calculating IMC
dataset_2016[,'IMC'] = dataset_2016[,'Weight.kg'] / (dataset_2016[,'Height.m'])^2
dataset_2017[,'IMC'] = dataset_2017[,'Weight.kg'] / (dataset_2017[,'Height.m'])^2


# Selecting PPGEE students
PPGEE_2016students <- dataset_2016[which(dataset_2016$Course == 'PPGEE'), ]


# Male students
male_students2016 <- PPGEE_2016students[which(PPGEE_2016students$Gender == 'M'), ]
male_students2017 <- dataset_2017[which(dataset_2017$Gender == 'M'), ]


# Female students
female_students2016 <- PPGEE_2016students[which(PPGEE_2016students$Gender == 'F'), ]
female_students2017 <- dataset_2017[which(dataset_2017$Gender == 'F'), ]


# Experiment dataset - Male x Female IMC
male_students <- rbind(male_students2016[model_var], male_students2017[model_var])
female_students <- rbind(female_students2016[model_var], female_students2017[model_var])

```