A fim de atuar nos três fatores citados, quatro cenários foram construídos a fim de melhor estudar os dados ([tabela 1](#tabela_1)):

<a id="tabela1"></a>

|| Longo Prazo | Curto Prazo |
|------------:|:------------|:------------|
| _Conservador_  | Baixa volatividade<br>Valorização dos preços nos últimos 2 anos| Baixa volatividade<br>Valorização dos preços nos últimos 6 meses |
| _Arrojado_     | Disposto a assumir alta volatividade<br>Valorização dos preços nos últimos 2 anos| Disposto a assumir alta volatividade<br>Valorização dos preços nos últimos 6 meses |

A partir disso, dado um valor para erro tipo 1 de $\alpha = 0.05$, as seguintes hipóteses são construídas:

## Hipotese 1: Baixa volatividade das ações
A fim de avaliar o quão volátil são os valores das ações, realiza-se um teste sobre os dados de cada empresa quanto à variação de seus fechamentos. Para realizar tal análise, será utilizado o indicador de volatividade de fechamento a fechamento [[1](https://web.archive.org/web/20100421083157/http://www.sitmo.com/eq/172)] com uma janela de tempo de 6 meses, aplicado durante toda série temporal. Assim, o indicador terá um valor próximo de zero para ações com baixa volatividade e vice-versa. Assim, formua-se a seguinte hipótese:

$$
\begin{cases} H_0: \overline{\mu_1} = \overline{\mu_2} = \overline{\mu_3} = \overline{\mu_4} = \overline{\mu_5} = 0&\\H_1: \overline{\mu_i} \neq 0 \text{ para, pelo menos, um i} \end{cases}
$$

Na hipótese definida acima, $\mu_n,n=1,2,3,4,5$ correspondem aos valores das médias do indicador das suas respectivas ações. A hipótese será testada utilizando o ANOVA[[2](https://en.wikipedia.org/wiki/Analysis_of_variance)], assumindo que os dados são independentes entre si, partem de uma distribuição normal e que possúem um mesmo erro padrão.

## Hipotese 2: Valoriação positiva dos preços em 2 anos
Com o objetivo de observar uma valorização das empresas, procura-se realizar um teste para avaliar se as ações estão em alta, baixa ou estagnadas. No caso, como o objetivo é indicar ações para se investir, a valorização positiva é almejada. Além disso, procura-se atender o caso de longo prazo, em que se estuda os valores nos dois anos mais recentes. Para esta análise será utilizada o percentual de valorização mensal. Assim, para considerar que uma ação está com valorização positiva, a média deve ser positiva.

$$
\begin{cases} H_0: \overline{\mu_1} = \overline{\mu_2} = \overline{\mu_3} = \overline{\mu_4} = \overline{\mu_5} > 0&\\H_1: \overline{\mu_i} \leq 0 \text{ para, pelo menos, um i}\end{cases}
$$
A partir da hipótese apresentada, em que $\mu_n,n=1,2,3,4,5$ correspondem às médias dos percentuais de valorização mensal de suas respectivas ações, realiza-se o ANOVA para a avaliação da hipótese considerando, assim como na hipótese anterior, que os dados são independentes entre si, partem de uma distribuição normal e que possúem um mesmo erro padrão.

## Hipotese 3: Valoriação positiva dos preços em 6 meses
Da mesma forma que a hipótese anterior, almeja-se avaliar se as ações estão em alta, baixa ou estagnadas, porém, procurando atender o caso de curto prazo. Ou seja, apenas os valores dos seis meses mais recentes serão utilizados para o estudo. Portanto, estipúla-se a seguinte hipótese:

$$
\begin{cases} H_0: \overline{\mu_1} = \overline{\mu_2} = \overline{\mu_3} = \overline{\mu_4} = \overline{\mu_5} > 0&\\H_1: \overline{\mu_i} \leq 0 \text{ para, pelo menos, um i}\end{cases}
$$

Assim como no caso anterior, em que $\mu_n,n=1,2,3,4,5$ correspondem às médias dos percentuais de valorização mensal de suas respectivas ações, realiza-se o ANOVA para a avaliação da hipótese utilizando as mesmas considerações que a hipótese anterior.