```{r loaddata, results='hide'}
# Function to convert absolute values on series to percentual
abs_serie_to_perct <- function(serie) {
  
  size = length(serie)
  serie_perct = numeric(size-1)
  
  for(i in 1:size-1) {
    vi = serie[i]
    vf = serie[i+1]
    perct_delta = (vf-vi)/vi
    serie_perct[i] <- perct_delta
  }
  
  return(serie_perct)
}


# Loading dataset
raw_data <- read.csv('../data/DadosAcoesGrupoA.csv', sep=',', header = FALSE)

# Reverse each series 
df <- raw_data[rev(1:nrow(raw_data)), ]

# Assign absolute values for each series
s1 <- df[,1]
s2 <- df[,2]
s3 <- df[,3]
s4 <- df[,4]
s5 <- df[,5]

# Assign percentual values for each series
sp1 <- abs_serie_to_perct(s1)
sp2 <- abs_serie_to_perct(s2)
sp3 <- abs_serie_to_perct(s3)
sp4 <- abs_serie_to_perct(s4)
sp5 <- abs_serie_to_perct(s5)

```




```{r short_term, results='hide'}

total_months = length(sp1)

sp1_short <- sp1[13:total_months]
sp2_short <- sp2[13:total_months]
sp3_short <- sp3[13:total_months]
sp4_short <- sp4[13:total_months]
sp5_short <- sp5[13:total_months]


```


```{r long_term, results='hide'}

total_months = length(sp1)

sp1_long <- sp1[(total_months-5):total_months]
sp2_long <- sp2[(total_months-5):total_months]
sp3_long <- sp3[(total_months-5):total_months]
sp4_long <- sp4[(total_months-5):total_months]
sp5_long <- sp5[(total_months-5):total_months]


```